/* Generated by Snowball 2.0.0 - https://snowballstem.org/ */


#include "steminternal.h"

namespace Xapian {

class InternalStemPolish : public SnowballStemImplementation {
    int I_pos;
    int r_remove_general_ends();
    int r_remove_plural_forms();
    int r_remove_adverbs_ends();
    int r_remove_verbs_ends();
    int r_remove_adjective_ends();
    int r_remove_dimunitive();
    int r_remove_nouns();

  public:

    InternalStemPolish();
    ~InternalStemPolish();
    int stem();
    std::string get_description() const;
};

}
