/* Generated by Snowball 2.0.0 - https://snowballstem.org/ */


#include "steminternal.h"

namespace Xapian {

class InternalStemSlovak : public SnowballStemImplementation {
    int I_p2;
    int I_p1;
    int r_end_vowel();
    int r_suffixes();
    int r_prefixes();
    int r_mark_p2();
    int r_mark_p1();
    int r_exception();
    int r_un_accent();
    int r_lower_case();
    int r_R2();

  public:

    InternalStemSlovak();
    ~InternalStemSlovak();
    int stem();
    std::string get_description() const;
};

}
